CREATE DATABASE SistemaVendasDB;
GO

USE SistemaVendasDB;
GO

CREATE TABLE CLIENTES (
	CLIENTE_ID INT IDENTITY PRIMARY KEY,
	NOME NVARCHAR(100),
	ENDERECO NVARCHAR(200),
	TELEFONE VARCHAR(20),
	EMAIL NVARCHAR(100)
);

CREATE TABLE PRODUTOS (
	PRODUTO_ID INT IDENTITY PRIMARY KEY,
	NOME NVARCHAR(100),
	CATEGORIA NVARCHAR(50),
	PRECO DECIMAL(10,2)
);

CREATE TABLE PEDIDOS (
	PEDIDO_ID INT IDENTITY PRIMARY KEY,
	CLIENTE_ID INT FOREIGN KEY REFERENCES CLIENTES(CLIENTE_ID),
	DATA_VENDA DATE
);

CREATE TABLE DETALHES_PEDIDO (
	DETALHE_ID INT IDENTITY PRIMARY KEY,
	PEDIDO_ID INT FOREIGN KEY REFERENCES PEDIDOS(PEDIDO_ID),
	PRODUTO_ID INT FOREIGN KEY REFERENCES PRODUTOS(PRODUTO_ID),
	QUANTIDADE INT,
	PRECO_UNITARIO DECIMAL(10,2)
);

CREATE TABLE NOTAS_FISCAIS (
	NOTA_ID INT IDENTITY PRIMARY KEY,
	PEDIDO_ID INT UNIQUE FOREIGN KEY REFERENCES PEDIDOS(PEDIDO_ID),
	NUMERO_NOTA VARCHAR(50),
	DATA_EMISSAO DATE,
	TOTAL DECIMAL(10,2)
)